/* GENERATED by tools/design_heartbeat.py. Do not edit: change the script and run it. */
/*
 * Fourth-order Butterworth high-pass at 36 Hz followed by a fourth-order Butterworth
 * low-pass at 62 Hz, 48 kHz. Above 120 Hz the low-pass approaches 24 dB/octave.
 * Each pair of second-order sections is low Q first. Each row is
 * {b0, b1, b2, a1, a2}, a0 = 1, for transposed direct form II.
 */

#ifndef PLS_HEARTBEAT_FILTER_COEFFICIENTS_H
#define PLS_HEARTBEAT_FILTER_COEFFICIENTS_H

namespace pls {

constexpr int kHeartbeatFilterSections = 4;
constexpr double kHeartbeatFilterSampleRate = 48000.0;
constexpr double kHeartbeatFilterHighpassHz = 36.0;
constexpr double kHeartbeatFilterLowpassHz = 62.0;

constexpr double kHeartbeatFilterCoefficients[kHeartbeatFilterSections][5] = {
    {0.99565968103175095, -1.9913193620635019, 0.99565968103175095, -1.9913083069095194, 0.99133041721748427},  // Q 0.541196
    {0.99819435804066636, -1.9963887160813327, 0.99819435804066636, -1.9963776327839542, 0.9963997993787107},  // Q 1.306563
    {1.6343840183535038e-05, 3.2687680367070077e-05, 1.6343840183535038e-05, -1.9850503821908723, 0.98511575755160641},  // Q 0.541196
    {1.6415403029301018e-05, 3.2830806058602036e-05, 1.6415403029301018e-05, -1.9937420882246555, 0.99380774983677256},  // Q 1.306563
};

}  // namespace pls

#endif  // PLS_HEARTBEAT_FILTER_COEFFICIENTS_H
