/* GENERATED by tools/design_highpass.py. Do not edit: change the script and run it. */
/*
 * 10th-order Chebyshev type II high-pass at 48 kHz: at least 30 dB down at and below
 * 62 Hz (designed for 30.001 dB), within 1 dB from 69.35 Hz up, 1.0 at Nyquist. Five
 * second-order sections, lowest Q first, run in this order. Each row is
 * {b0, b1, b2, a1, a2}, a0 = 1: y = b0 x + b1 x[-1] + b2 x[-2] - a1 y[-1] - a2 y[-2].
 */

#ifndef PLS_HIGHPASS_COEFFICIENTS_H
#define PLS_HIGHPASS_COEFFICIENTS_H

namespace pls {

constexpr int kHighpassSections = 5;
constexpr double kHighpassSampleRate = 48000.0;
constexpr double kHighpassStopbandEdgeHz = 62.0;
constexpr double kHighpassStopbandDb = 30.0;

constexpr double kHighpassCoefficients[kHighpassSections][5] = {
    {0.99658847845260989, -1.9931753505337648, 0.99658847845260989, -1.9931693753713384, 0.99318293206764607},  // Q 0.5392
    {0.99692111140877582, -1.9938286890642027, 0.99692111140877582, -1.993822711925314, 0.99384819995644025},  // Q 0.8194
    {0.99755442257135751, -1.9950759926418393, 0.99755442257135751, -1.995070011734815, 0.99511482604973933},  // Q 1.3687
    {0.99842740476649938, -1.9968026014205025, 0.99842740476649938, -1.996796615308422, 0.99686079564507957},  // Q 2.5500
    {0.99945560046537141, -1.9988469821889729, 0.99945560046537141, -1.9988409899302253, 0.99891719318949024},  // Q 8.0596
};

}  // namespace pls

#endif  // PLS_HIGHPASS_COEFFICIENTS_H
