"""Design the heartbeat voice's 36-62 Hz shaping and write its C++ coefficients.

The voice is a 44 Hz sine under a smooth finite envelope. Multiplication by that envelope creates
sidebands. The native layer therefore follows it with fourth-order Butterworth high- and low-pass
sections at the edges of its reserved 36-62 Hz band. The four low-pass poles give at least the
specified 24 dB/octave roll-off above 120 Hz; 120 Hz is not treated as a corner or as an invented
attenuation target.

The four digital biquads use the RBJ bilinear-transform form at 48 kHz. Their Butterworth Q values
are derived here, rather than copied from a filter-design package. The native and Python tests
measure the complete finite voice, including its windowed tail, not only this filter response.

    python tools/design_heartbeat.py            writes the header
    python tools/design_heartbeat.py --check    exits 1 if the committed header differs
"""

from __future__ import annotations

import argparse
import cmath
import math
import re
import sys
from pathlib import Path

FS = 48_000.0
ORDER = 4
HIGHPASS_HZ = 36.0
LOWPASS_HZ = 62.0
TABLE_HZ = (44, 62, 120, 240, 250, 480, 1_000)

HEADER = (
    Path(__file__).resolve().parent.parent / "native" / "src" / "heartbeat_filter_coefficients.h"
)


def butterworth(cutoff_hz: float, *, highpass: bool) -> list[tuple[float, ...]]:
    """Two (b0, b1, b2, a1, a2, Q) sections, low Q first."""
    omega = 2.0 * math.pi * cutoff_hz / FS
    cosine, sine = math.cos(omega), math.sin(omega)
    sections = []
    for k in range(ORDER // 2):
        q = 1.0 / (2.0 * math.cos((2 * k + 1) * math.pi / (2.0 * ORDER)))
        alpha = sine / (2.0 * q)
        a0 = 1.0 + alpha
        numerator = 1.0 + cosine if highpass else 1.0 - cosine
        b0 = numerator / (2.0 * a0)
        b1 = -2.0 * b0 if highpass else 2.0 * b0
        sections.append(
            (b0, b1, b0, -2.0 * cosine / a0, (1.0 - alpha) / a0, q)
        )
    return sections


def design() -> list[tuple[float, ...]]:
    """The high-pass first, then the low-pass; each is fourth order."""
    return butterworth(HIGHPASS_HZ, highpass=True) + butterworth(LOWPASS_HZ, highpass=False)


def magnitude_db(sections, hz: float) -> float:
    z1 = cmath.exp(-2j * math.pi * hz / FS)
    z2 = z1 * z1
    response = complex(1.0)
    for b0, b1, b2, a1, a2, *_ in sections:
        response *= (b0 + b1 * z1 + b2 * z2) / (1.0 + a1 * z1 + a2 * z2)
    return 20.0 * math.log10(abs(response))


def render_header(sections) -> str:
    lines = [
        "/* GENERATED by tools/design_heartbeat.py. Do not edit: change the script and run it. */",
        "/*",
        " * Fourth-order Butterworth high-pass at 36 Hz followed by a fourth-order Butterworth",
        " * low-pass at 62 Hz, 48 kHz. Above 120 Hz the low-pass approaches 24 dB/octave.",
        " * Each pair of second-order sections is low Q first. Each row is",
        " * {b0, b1, b2, a1, a2}, a0 = 1, for transposed direct form II.",
        " */",
        "",
        "#ifndef PLS_HEARTBEAT_FILTER_COEFFICIENTS_H",
        "#define PLS_HEARTBEAT_FILTER_COEFFICIENTS_H",
        "",
        "namespace pls {",
        "",
        f"constexpr int kHeartbeatFilterSections = {len(sections)};",
        f"constexpr double kHeartbeatFilterSampleRate = {FS:.1f};",
        f"constexpr double kHeartbeatFilterHighpassHz = {HIGHPASS_HZ:.1f};",
        f"constexpr double kHeartbeatFilterLowpassHz = {LOWPASS_HZ:.1f};",
        "",
        "constexpr double kHeartbeatFilterCoefficients[kHeartbeatFilterSections][5] = {",
    ]
    for b0, b1, b2, a1, a2, q in sections:
        values = ", ".join(f"{v:.17g}" for v in (b0, b1, b2, a1, a2))
        lines.append(f"    {{{values}}},  // Q {q:.6f}")
    lines += [
        "};",
        "",
        "}  // namespace pls",
        "",
        "#endif  // PLS_HEARTBEAT_FILTER_COEFFICIENTS_H",
        "",
    ]
    return "\n".join(lines)


def parse_coefficients(text: str) -> list[tuple[float, ...]]:
    body = text.split("kHeartbeatFilterCoefficients[", 1)[1]
    rows = re.findall(r"\{([^{}]+)\}", body)
    return [tuple(float(value) for value in row.split(",")) for row in rows]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="compare with the committed header")
    args = parser.parse_args()

    sections = design()
    text = render_header(sections)
    written = parse_coefficients(text)
    for hz in TABLE_HZ:
        print(f"{hz:>7g} Hz  {magnitude_db(written, hz):>9.3f} dB")

    # At each Butterworth edge the other half of the band-pass also contributes a little. Check
    # each constituent design at its own -3.0103 dB corner instead of pretending the cascade is.
    highpass_corner = magnitude_db(butterworth(HIGHPASS_HZ, highpass=True), HIGHPASS_HZ)
    lowpass_corner = magnitude_db(butterworth(LOWPASS_HZ, highpass=False), LOWPASS_HZ)
    if not -3.011 < highpass_corner < -3.010:
        print(f"FAIL 36 Hz high-pass corner is {highpass_corner:.6f} dB", file=sys.stderr)
        return 1
    if not -3.011 < lowpass_corner < -3.010:
        print(f"FAIL 62 Hz low-pass corner is {lowpass_corner:.6f} dB", file=sys.stderr)
        return 1
    # From 120 Hz upward, successive octaves must exhibit the requested fourth-order slope.
    if magnitude_db(written, 240.0) - magnitude_db(written, 120.0) > -23.0:
        print("FAIL response above 120 Hz does not roll off at 24 dB/octave", file=sys.stderr)
        return 1
    if magnitude_db(written, 480.0) - magnitude_db(written, 240.0) > -23.7:
        print("FAIL second octave above 120 Hz does not approach 24 dB/octave", file=sys.stderr)
        return 1

    if args.check:
        committed = HEADER.read_bytes().replace(b"\r\n", b"\n").decode("utf-8")
        if committed != text:
            print(f"{HEADER} differs from the design: run this script", file=sys.stderr)
            return 1
        print(f"{HEADER} matches")
        return 0
    HEADER.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {HEADER}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
